/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.pharmacy.app.GUI.Sales;
//import pharmacymanagement.gui.Promo.HomePromo;
import com.pharmacy.app.GUI.Sales.InvoicePanel;
import com.pharmacy.app.GUI.Sales.SalesPanel;
import java.awt.CardLayout;

/**
 *
 * @author Giai Cuu Li San
 */
public class HomeSales extends javax.swing.JFrame {
    
    private SalesPanel salesPanel;
    private InvoicePanel invoicePanel;
//    private HomePromo homePromoPanel;
    /**
     * Creates new form HomeSales
     */
    public HomeSales() {
        initComponents();
        salesPanel = new SalesPanel();
        invoicePanel = new InvoicePanel();
//        homePromoPanel = new HomePromo();
        
        ContentPanel.add(salesPanel, "sales");
        ContentPanel.add(invoicePanel, "invoice");
//        ContentPanel.add(homePromoPanel, "promo");
        
        
        CardLayout card = (CardLayout) ContentPanel.getLayout();
        card.show(ContentPanel, "sales");
        ContentPanel.revalidate();
        ContentPanel.repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ContentPanel = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuBanHang = new javax.swing.JMenu();
        menuHoaDon = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1060, 700));

        ContentPanel.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        ContentPanel.setPreferredSize(new java.awt.Dimension(1050, 650));
        ContentPanel.setLayout(new java.awt.CardLayout());

        jMenuBar1.setPreferredSize(new java.awt.Dimension(200, 23));

        menuBanHang.setText("Bán hàng");
        menuBanHang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuBanHangMouseClicked(evt);
            }
        });
        menuBanHang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuBanHangActionPerformed(evt);
            }
        });
        jMenuBar1.add(menuBanHang);

        menuHoaDon.setText("Hóa đơn");
        menuHoaDon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuHoaDonMouseClicked(evt);
            }
        });
        jMenuBar1.add(menuHoaDon);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ContentPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(ContentPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 70, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuBanHangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuBanHangMouseClicked
        System.out.println("pharmacymanagement.gui.Sales.HomeSales.menuBanHangMouseClicked()");
        CardLayout card = (CardLayout) ContentPanel.getLayout();
        card.show(ContentPanel, "sales");
        ContentPanel.revalidate();
        ContentPanel.repaint();
    }//GEN-LAST:event_menuBanHangMouseClicked

    private void menuHoaDonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuHoaDonMouseClicked
        System.out.println("pharmacymanagement.gui.Sales.HomeSales.menuHoaDonMouseClicked()");
        CardLayout card = (CardLayout) ContentPanel.getLayout();
        card.show(ContentPanel, "invoice");
        ContentPanel.revalidate();
        ContentPanel.repaint();
    }//GEN-LAST:event_menuHoaDonMouseClicked

    private void menuBanHangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuBanHangActionPerformed

    }//GEN-LAST:event_menuBanHangActionPerformed

                                                

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HomeSales.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HomeSales.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HomeSales.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HomeSales.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HomeSales().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel ContentPanel;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu menuBanHang;
    private javax.swing.JMenu menuHoaDon;
    // End of variables declaration//GEN-END:variables
}

