/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.pharmacy.app.GUI.Sales;

/**
 *
 * @author Giai Cuu Li San
 */
public class InvoicePanel extends javax.swing.JPanel {

    /**
     * Creates new form HomePromo
     */
    public InvoicePanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        txtSearch = new javax.swing.JTextField();
        cbxAll = new javax.swing.JComboBox<>();
        jPanel3 = new javax.swing.JPanel();
        jButton4 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblPromo = new javax.swing.JTable();

        setMaximumSize(new java.awt.Dimension(326589, 326589));
        setMinimumSize(new java.awt.Dimension(600, 500));
        setPreferredSize(new java.awt.Dimension(1200, 800));
        setLayout(new java.awt.BorderLayout());

        jPanel2.setMaximumSize(new java.awt.Dimension(800, 50));
        jPanel2.setMinimumSize(new java.awt.Dimension(800, 54));
        jPanel2.setPreferredSize(new java.awt.Dimension(800, 50));
        jPanel2.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 0, 0));

        jPanel4.setMinimumSize(new java.awt.Dimension(400, 40));
        jPanel4.setPreferredSize(new java.awt.Dimension(500, 70));
        jPanel4.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 20, 15));

        txtSearch.setText("Search");
        txtSearch.setMinimumSize(new java.awt.Dimension(80, 30));
        txtSearch.setPreferredSize(new java.awt.Dimension(250, 30));
        jPanel4.add(txtSearch);

        cbxAll.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "All", "Active", "IsActive" }));
        cbxAll.setMinimumSize(new java.awt.Dimension(75, 25));
        cbxAll.setPreferredSize(new java.awt.Dimension(80, 30));
        jPanel4.add(cbxAll);

        jPanel2.add(jPanel4);

        jPanel3.setMinimumSize(new java.awt.Dimension(500, 40));
        jPanel3.setPreferredSize(new java.awt.Dimension(500, 70));
        jPanel3.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT, 20, 15));

        jButton4.setText("Refresh");
        jButton4.setMaximumSize(new java.awt.Dimension(326589, 326589));
        jButton4.setMinimumSize(new java.awt.Dimension(0, 0));
        jButton4.setPreferredSize(new java.awt.Dimension(72, 30));
        jPanel3.add(jButton4);

        jButton2.setText("Print");
        jButton2.setMaximumSize(new java.awt.Dimension(326589, 326589));
        jButton2.setMinimumSize(new java.awt.Dimension(0, 0));
        jButton2.setPreferredSize(new java.awt.Dimension(80, 30));
        jPanel3.add(jButton2);

        jPanel2.add(jPanel3);

        add(jPanel2, java.awt.BorderLayout.PAGE_START);

        jPanel1.setMinimumSize(new java.awt.Dimension(800, 550));
        jPanel1.setPreferredSize(new java.awt.Dimension(1200, 800));

        jScrollPane2.setMinimumSize(new java.awt.Dimension(760, 510));
        jScrollPane2.setPreferredSize(new java.awt.Dimension(1180, 700));

        tblPromo.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tblPromo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"HD01", "Nguyen Van B", null, "101000"},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Mã hóa đơn", "Họ tên khách hàng", "Ngày mua", "Tổng tiền"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Object.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tblPromo.setMaximumSize(new java.awt.Dimension(326589, 326589));
        tblPromo.setMinimumSize(new java.awt.Dimension(0, 0));
        tblPromo.setPreferredSize(new java.awt.Dimension(1000, 600));
        tblPromo.setShowGrid(true);
        tblPromo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tblPromoMousePressed(evt);
            }
        });
        jScrollPane2.setViewportView(tblPromo);

        jPanel1.add(jScrollPane2);

        add(jPanel1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void tblPromoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblPromoMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_tblPromoMousePressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cbxAll;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tblPromo;
    private javax.swing.JTextField txtSearch;
    // End of variables declaration//GEN-END:variables
}
