/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.pharmacy.app.GUI.Sales;
import javax.swing.JFrame;
import javax.swing.SwingUtilities;
/**
 *
 * @author Giai Cuu Li San
 */
public class SalesPanel extends javax.swing.JPanel {
    /**
     * Creates new form PromoHome
     */
    public SalesPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        txtSearch = new javax.swing.JTextField();
        cbxAll = new javax.swing.JComboBox<>();
        jPanel3 = new javax.swing.JPanel();
        btnAddMedicineToCart = new javax.swing.JButton();
        btnRefresh = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblPromo = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jPanel11 = new javax.swing.JPanel();
        jSpinner1 = new javax.swing.JSpinner();
        jTextField8 = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        btnDelete1LineInCart = new javax.swing.JButton();
        btnReset = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jPanel13 = new javax.swing.JPanel();
        lblPhoneCustomer = new javax.swing.JLabel();
        lblNameCustomer = new javax.swing.JLabel();
        lblPointCustomer = new javax.swing.JLabel();
        jPanel12 = new javax.swing.JPanel();
        txtPhoneCustomer = new javax.swing.JTextField();
        txtNameCustomer = new javax.swing.JTextField();
        txtPointCustomer = new javax.swing.JTextField();
        jPanel7 = new javax.swing.JPanel();
        jPanel14 = new javax.swing.JPanel();
        lblTotalProductPrice = new javax.swing.JLabel();
        lblProductDiscount = new javax.swing.JLabel();
        lblVoucher = new javax.swing.JLabel();
        lblVoucherDiscount = new javax.swing.JLabel();
        lblSubtotal = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jPanel15 = new javax.swing.JPanel();
        txtTotalProductPrice = new javax.swing.JTextField();
        txtProductDiscoun = new javax.swing.JTextField();
        txtVoucher = new javax.swing.JTextField();
        txtVoucherDiscount = new javax.swing.JTextField();
        txtSubtotal = new javax.swing.JTextField();
        btnPayment = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(1000, 650));

        jPanel1.setPreferredSize(new java.awt.Dimension(650, 650));
        jPanel1.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 5, 10));

        jPanel4.setMinimumSize(new java.awt.Dimension(400, 40));
        jPanel4.setPreferredSize(new java.awt.Dimension(640, 40));
        jPanel4.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 10, 10));

        txtSearch.setText("Tìm kiếm thuốc");
        txtSearch.setMinimumSize(new java.awt.Dimension(80, 30));
        txtSearch.setPreferredSize(new java.awt.Dimension(250, 22));
        jPanel4.add(txtSearch);

        cbxAll.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "All", "Active", "IsActive" }));
        cbxAll.setPreferredSize(new java.awt.Dimension(80, 22));
        jPanel4.add(cbxAll);

        jPanel3.setPreferredSize(new java.awt.Dimension(280, 30));
        jPanel3.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT, 10, 5));

        btnAddMedicineToCart.setText("Thêm thuốc");
        jPanel3.add(btnAddMedicineToCart);

        btnRefresh.setText("Refresh");
        jPanel3.add(btnRefresh);

        jPanel4.add(jPanel3);

        jPanel1.add(jPanel4);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Danh sách thuốc");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel1.setPreferredSize(new java.awt.Dimension(200, 16));
        jPanel1.add(jLabel1);

        jScrollPane2.setMinimumSize(new java.awt.Dimension(760, 510));
        jScrollPane2.setPreferredSize(new java.awt.Dimension(620, 250));

        tblPromo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"123", "Parnadol", "vỉ",  new Float(30000.0),  new Integer(200), "22/12/2025", null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Mã thuốc", "Tên thuốc", "Đơn vị", "Đơn giá", "Tồn kho", "Hạn sử dụng", "Khuyến mãi (%)"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Float.class, java.lang.Integer.class, java.lang.Object.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tblPromo.setMaximumSize(new java.awt.Dimension(700, 600));
        tblPromo.setMinimumSize(new java.awt.Dimension(700, 450));
        tblPromo.setPreferredSize(new java.awt.Dimension(600, 300));
        tblPromo.setShowGrid(true);
        tblPromo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tblPromoMousePressed(evt);
            }
        });
        jScrollPane2.setViewportView(tblPromo);

        jPanel1.add(jScrollPane2);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("Giỏ hàng");
        jLabel2.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jLabel2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel2.setPreferredSize(new java.awt.Dimension(80, 30));
        jLabel2.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jPanel1.add(jLabel2);

        jPanel11.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel11.setPreferredSize(new java.awt.Dimension(620, 200));

        jTextField8.setText("Parnadol");

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel11Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addComponent(jSpinner1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(418, Short.MAX_VALUE))
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSpinner1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(154, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel11);

        jPanel5.setPreferredSize(new java.awt.Dimension(640, 70));
        jPanel5.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT, 10, 0));

        btnDelete1LineInCart.setText("Xóa");
        jPanel5.add(btnDelete1LineInCart);

        btnReset.setText("Đặt lại");
        btnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetActionPerformed(evt);
            }
        });
        jPanel5.add(btnReset);

        jPanel1.add(jPanel5);

        add(jPanel1);

        jPanel2.setPreferredSize(new java.awt.Dimension(340, 650));
        jPanel2.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 5, 20));

        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Thông tin khách hàng", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 14))); // NOI18N
        jPanel6.setPreferredSize(new java.awt.Dimension(330, 150));
        jPanel6.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 15, 10));

        jPanel13.setPreferredSize(new java.awt.Dimension(150, 100));
        jPanel13.setLayout(new java.awt.GridLayout(3, 1, 0, 10));

        lblPhoneCustomer.setText("Số điện thoại khách hàng");
        lblPhoneCustomer.setPreferredSize(new java.awt.Dimension(100, 16));
        jPanel13.add(lblPhoneCustomer);

        lblNameCustomer.setText("Tên khách hàng");
        jPanel13.add(lblNameCustomer);

        lblPointCustomer.setText("Điểm tích lũy");
        jPanel13.add(lblPointCustomer);

        jPanel6.add(jPanel13);

        jPanel12.setMinimumSize(new java.awt.Dimension(300, 350));
        jPanel12.setPreferredSize(new java.awt.Dimension(100, 100));
        jPanel12.setLayout(new java.awt.GridLayout(3, 1, 5, 10));

        txtPhoneCustomer.setPreferredSize(new java.awt.Dimension(200, 22));
        jPanel12.add(txtPhoneCustomer);

        txtNameCustomer.setEnabled(false);
        jPanel12.add(txtNameCustomer);

        txtPointCustomer.setEnabled(false);
        txtPointCustomer.setPreferredSize(new java.awt.Dimension(73, 25));
        jPanel12.add(txtPointCustomer);

        jPanel6.add(jPanel12);

        jPanel2.add(jPanel6);

        jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Thanh toán", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 14))); // NOI18N
        jPanel7.setPreferredSize(new java.awt.Dimension(330, 250));

        jPanel14.setPreferredSize(new java.awt.Dimension(150, 200));
        jPanel14.setLayout(new java.awt.GridLayout(6, 1, 0, 15));

        lblTotalProductPrice.setText("Tổng tiền sản phẩm");
        lblTotalProductPrice.setPreferredSize(new java.awt.Dimension(100, 16));
        jPanel14.add(lblTotalProductPrice);

        lblProductDiscount.setText("Tiền giảm trên sản phẩm");
        jPanel14.add(lblProductDiscount);

        lblVoucher.setText("Voucher");
        jPanel14.add(lblVoucher);

        lblVoucherDiscount.setText("Tiền giảm từ voucher");
        jPanel14.add(lblVoucherDiscount);

        lblSubtotal.setText("Tạm tính");
        jPanel14.add(lblSubtotal);
        jPanel14.add(jLabel14);

        jPanel7.add(jPanel14);

        jPanel15.setMinimumSize(new java.awt.Dimension(300, 350));
        jPanel15.setPreferredSize(new java.awt.Dimension(100, 200));
        jPanel15.setLayout(new java.awt.GridLayout(6, 1, 5, 10));

        txtTotalProductPrice.setEnabled(false);
        txtTotalProductPrice.setPreferredSize(new java.awt.Dimension(200, 22));
        jPanel15.add(txtTotalProductPrice);

        txtProductDiscoun.setEnabled(false);
        jPanel15.add(txtProductDiscoun);

        txtVoucher.setEnabled(false);
        txtVoucher.setPreferredSize(new java.awt.Dimension(73, 25));
        jPanel15.add(txtVoucher);

        txtVoucherDiscount.setEnabled(false);
        jPanel15.add(txtVoucherDiscount);

        txtSubtotal.setEnabled(false);
        jPanel15.add(txtSubtotal);

        btnPayment.setText("Thanh toán");
        btnPayment.setPreferredSize(new java.awt.Dimension(91, 30));
        btnPayment.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnPaymentMouseClicked(evt);
            }
        });
        btnPayment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPaymentActionPerformed(evt);
            }
        });
        jPanel15.add(btnPayment);

        jPanel7.add(jPanel15);

        jPanel2.add(jPanel7);

        add(jPanel2);
    }// </editor-fold>//GEN-END:initComponents

    private void tblPromoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblPromoMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_tblPromoMousePressed

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnResetActionPerformed

    private void btnPaymentMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPaymentMouseClicked
     
    }//GEN-LAST:event_btnPaymentMouseClicked

    private void btnPaymentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPaymentActionPerformed
        PaymentDialog dialog = new PaymentDialog((JFrame) SwingUtilities.getWindowAncestor(this), true);
        dialog.setVisible(true);
    }//GEN-LAST:event_btnPaymentActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddMedicineToCart;
    private javax.swing.JButton btnDelete1LineInCart;
    private javax.swing.JButton btnPayment;
    private javax.swing.JButton btnRefresh;
    private javax.swing.JButton btnReset;
    private javax.swing.JComboBox<String> cbxAll;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JLabel lblNameCustomer;
    private javax.swing.JLabel lblPhoneCustomer;
    private javax.swing.JLabel lblPointCustomer;
    private javax.swing.JLabel lblProductDiscount;
    private javax.swing.JLabel lblSubtotal;
    private javax.swing.JLabel lblTotalProductPrice;
    private javax.swing.JLabel lblVoucher;
    private javax.swing.JLabel lblVoucherDiscount;
    private javax.swing.JTable tblPromo;
    private javax.swing.JTextField txtNameCustomer;
    private javax.swing.JTextField txtPhoneCustomer;
    private javax.swing.JTextField txtPointCustomer;
    private javax.swing.JTextField txtProductDiscoun;
    private javax.swing.JTextField txtSearch;
    private javax.swing.JTextField txtSubtotal;
    private javax.swing.JTextField txtTotalProductPrice;
    private javax.swing.JTextField txtVoucher;
    private javax.swing.JTextField txtVoucherDiscount;
    // End of variables declaration//GEN-END:variables
}
