/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.pharmacy.app.GUI.Authorization;

/**
 *
 * @author phong
 */
public class AuthorizationManagement extends javax.swing.JPanel {

    /**
     * Creates new form AuthorizationManagement
     */
    public AuthorizationManagement() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        pnlRole = new javax.swing.JPanel();
        pnlRoleList = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbRole = new javax.swing.JTable();
        pnlAuthorization = new javax.swing.JPanel();
        txtSearchRole = new javax.swing.JTextField();
        pnlButton = new javax.swing.JPanel();
        btnAddRole = new javax.swing.JButton();
        btnRefeshRole = new javax.swing.JButton();
        btnPdf = new javax.swing.JButton();
        pnlPermission = new javax.swing.JPanel();
        pnlPermission1 = new javax.swing.JPanel();
        txtSearchPermission = new javax.swing.JTextField();
        pnlButton1 = new javax.swing.JPanel();
        btnAddPermission = new javax.swing.JButton();
        btnRefeshRole1 = new javax.swing.JButton();
        btnPdf1 = new javax.swing.JButton();
        pnlPermissionList = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblPermission = new javax.swing.JTable();

        setLayout(new java.awt.BorderLayout());

        jTabbedPane1.setBackground(new java.awt.Color(255, 255, 255));

        pnlRole.setBackground(new java.awt.Color(255, 255, 255));
        pnlRole.setLayout(new java.awt.BorderLayout());

        pnlRoleList.setBackground(new java.awt.Color(255, 255, 255));
        pnlRoleList.setPreferredSize(new java.awt.Dimension(600, 439));

        jScrollPane1.setPreferredSize(new java.awt.Dimension(580, 402));

        tbRole.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "ID", "Vai trò"
            }
        ));
        tbRole.setFocusable(false);
        tbRole.setMinimumSize(new java.awt.Dimension(500, 80));
        tbRole.setPreferredSize(new java.awt.Dimension(500, 80));
        tbRole.setShowGrid(true);
        jScrollPane1.setViewportView(tbRole);

        pnlRoleList.add(jScrollPane1);

        pnlRole.add(pnlRoleList, java.awt.BorderLayout.CENTER);

        pnlAuthorization.setBackground(new java.awt.Color(255, 255, 255));
        pnlAuthorization.setToolTipText("");
        pnlAuthorization.setPreferredSize(new java.awt.Dimension(607, 40));
        pnlAuthorization.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 10, 5));

        txtSearchRole.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        txtSearchRole.setForeground(new java.awt.Color(153, 153, 153));
        txtSearchRole.setText("Tìm kiếm");
        txtSearchRole.setHighlighter(null);
        txtSearchRole.setMinimumSize(new java.awt.Dimension(260, 22));
        txtSearchRole.setPreferredSize(new java.awt.Dimension(260, 22));
        pnlAuthorization.add(txtSearchRole);

        pnlButton.setBackground(new java.awt.Color(255, 255, 255));
        pnlButton.setPreferredSize(new java.awt.Dimension(320, 35));
        pnlButton.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT, 10, 5));

        btnAddRole.setText("Thêm");
        btnAddRole.setFocusable(false);
        btnAddRole.setMaximumSize(new java.awt.Dimension(72, 22));
        btnAddRole.setMinimumSize(new java.awt.Dimension(72, 22));
        btnAddRole.setPreferredSize(new java.awt.Dimension(72, 22));
        pnlButton.add(btnAddRole);

        btnRefeshRole.setText("Tải lại");
        btnRefeshRole.setFocusable(false);
        btnRefeshRole.setMaximumSize(new java.awt.Dimension(72, 22));
        btnRefeshRole.setMinimumSize(new java.awt.Dimension(72, 22));
        btnRefeshRole.setPreferredSize(new java.awt.Dimension(72, 22));
        pnlButton.add(btnRefeshRole);

        btnPdf.setText("In PDF");
        btnPdf.setFocusable(false);
        btnPdf.setMaximumSize(new java.awt.Dimension(72, 22));
        btnPdf.setMinimumSize(new java.awt.Dimension(72, 22));
        btnPdf.setPreferredSize(new java.awt.Dimension(72, 22));
        pnlButton.add(btnPdf);

        pnlAuthorization.add(pnlButton);

        pnlRole.add(pnlAuthorization, java.awt.BorderLayout.PAGE_START);

        jTabbedPane1.addTab("Nhóm quyền", pnlRole);

        pnlPermission.setBackground(new java.awt.Color(255, 255, 255));
        pnlPermission.setLayout(new java.awt.BorderLayout());

        pnlPermission1.setBackground(new java.awt.Color(255, 255, 255));
        pnlPermission1.setToolTipText("");
        pnlPermission1.setPreferredSize(new java.awt.Dimension(607, 40));
        pnlPermission1.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 10, 5));

        txtSearchPermission.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        txtSearchPermission.setForeground(new java.awt.Color(153, 153, 153));
        txtSearchPermission.setText("Tìm kiếm");
        txtSearchPermission.setHighlighter(null);
        txtSearchPermission.setMinimumSize(new java.awt.Dimension(260, 22));
        txtSearchPermission.setPreferredSize(new java.awt.Dimension(260, 22));
        pnlPermission1.add(txtSearchPermission);

        pnlButton1.setBackground(new java.awt.Color(255, 255, 255));
        pnlButton1.setPreferredSize(new java.awt.Dimension(320, 35));
        pnlButton1.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT, 10, 5));

        btnAddPermission.setText("Thêm");
        btnAddPermission.setFocusable(false);
        btnAddPermission.setMaximumSize(new java.awt.Dimension(72, 22));
        btnAddPermission.setMinimumSize(new java.awt.Dimension(72, 22));
        btnAddPermission.setPreferredSize(new java.awt.Dimension(72, 22));
        pnlButton1.add(btnAddPermission);

        btnRefeshRole1.setText("Tải lại");
        btnRefeshRole1.setFocusable(false);
        btnRefeshRole1.setMaximumSize(new java.awt.Dimension(72, 22));
        btnRefeshRole1.setMinimumSize(new java.awt.Dimension(72, 22));
        btnRefeshRole1.setPreferredSize(new java.awt.Dimension(72, 22));
        pnlButton1.add(btnRefeshRole1);

        btnPdf1.setText("In PDF");
        btnPdf1.setFocusable(false);
        btnPdf1.setMaximumSize(new java.awt.Dimension(72, 22));
        btnPdf1.setMinimumSize(new java.awt.Dimension(72, 22));
        btnPdf1.setPreferredSize(new java.awt.Dimension(72, 22));
        pnlButton1.add(btnPdf1);

        pnlPermission1.add(pnlButton1);

        pnlPermission.add(pnlPermission1, java.awt.BorderLayout.NORTH);

        pnlPermissionList.setBackground(new java.awt.Color(255, 255, 255));
        pnlPermissionList.setPreferredSize(new java.awt.Dimension(600, 439));

        jScrollPane2.setPreferredSize(new java.awt.Dimension(580, 402));

        tblPermission.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "ID", "Quyền"
            }
        ));
        tblPermission.setFocusable(false);
        tblPermission.setMinimumSize(new java.awt.Dimension(500, 80));
        tblPermission.setPreferredSize(new java.awt.Dimension(500, 80));
        tblPermission.setShowGrid(true);
        jScrollPane2.setViewportView(tblPermission);

        pnlPermissionList.add(jScrollPane2);

        pnlPermission.add(pnlPermissionList, java.awt.BorderLayout.CENTER);

        jTabbedPane1.addTab("Quyền", pnlPermission);

        add(jTabbedPane1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddPermission;
    private javax.swing.JButton btnAddRole;
    private javax.swing.JButton btnPdf;
    private javax.swing.JButton btnPdf1;
    private javax.swing.JButton btnRefeshRole;
    private javax.swing.JButton btnRefeshRole1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JPanel pnlAuthorization;
    private javax.swing.JPanel pnlButton;
    private javax.swing.JPanel pnlButton1;
    private javax.swing.JPanel pnlPermission;
    private javax.swing.JPanel pnlPermission1;
    private javax.swing.JPanel pnlPermissionList;
    private javax.swing.JPanel pnlRole;
    private javax.swing.JPanel pnlRoleList;
    private javax.swing.JTable tbRole;
    private javax.swing.JTable tblPermission;
    private javax.swing.JTextField txtSearchPermission;
    private javax.swing.JTextField txtSearchRole;
    // End of variables declaration//GEN-END:variables
}
