/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.pharmacy.app.GUI.Customer;

import com.pharmacy.app.GUI.Promo.AddPromo;
import java.awt.event.ActionEvent;
import javax.swing.JFrame;
import javax.swing.SwingUtilities;

/**
 *
 * @author BOI QUAN
 */
public class CustomerList extends javax.swing.JPanel {

    /**
     * Creates new form CustomerList
     */
    public CustomerList() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        plHeader = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        plSearch = new javax.swing.JPanel();
        cbSort = new javax.swing.JComboBox<>();
        txtSearch1 = new javax.swing.JTextField();
        plButton = new javax.swing.JPanel();
        btnAdd = new javax.swing.JButton();
        btnRefesh = new javax.swing.JButton();
        lblImg = new javax.swing.JLabel();
        plCustomerList = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbCustomerList = new javax.swing.JTable();

        setBackground(new java.awt.Color(255, 255, 255));
        setMaximumSize(new java.awt.Dimension(326589, 326589));
        setMinimumSize(new java.awt.Dimension(986, 578));
        setPreferredSize(new java.awt.Dimension(986, 578));
        setLayout(new java.awt.BorderLayout());

        plHeader.setBackground(new java.awt.Color(255, 255, 255));
        plHeader.setMaximumSize(new java.awt.Dimension(800, 100));
        plHeader.setMinimumSize(new java.awt.Dimension(800, 100));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("QUẢN LÝ KHÁCH HÀNG");

        plSearch.setBackground(new java.awt.Color(255, 255, 255));
        plSearch.setMaximumSize(new java.awt.Dimension(450, 70));
        plSearch.setMinimumSize(new java.awt.Dimension(450, 70));
        plSearch.setPreferredSize(new java.awt.Dimension(450, 70));
        plSearch.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 20, 20));

        cbSort.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbSort.setMinimumSize(new java.awt.Dimension(100, 30));
        cbSort.setPreferredSize(new java.awt.Dimension(100, 30));
        plSearch.add(cbSort);

        txtSearch1.setMaximumSize(new java.awt.Dimension(300, 30));
        txtSearch1.setMinimumSize(new java.awt.Dimension(300, 30));
        txtSearch1.setPreferredSize(new java.awt.Dimension(300, 30));
        plSearch.add(txtSearch1);

        plButton.setBackground(new java.awt.Color(255, 255, 255));
        plButton.setMaximumSize(new java.awt.Dimension(300, 70));
        plButton.setMinimumSize(new java.awt.Dimension(300, 70));
        plButton.setPreferredSize(new java.awt.Dimension(300, 70));
        plButton.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 20, 15));

        btnAdd.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnAdd.setText("Thêm");
        btnAdd.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnAdd.setMaximumSize(new java.awt.Dimension(75, 30));
        btnAdd.setMinimumSize(new java.awt.Dimension(75, 30));
        btnAdd.setPreferredSize(new java.awt.Dimension(75, 30));
        plButton.add(btnAdd);

        btnRefesh.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnRefesh.setText("Làm mới");
        btnRefesh.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnRefesh.setMaximumSize(new java.awt.Dimension(90, 30));
        btnRefesh.setMinimumSize(new java.awt.Dimension(90, 30));
        btnRefesh.setPreferredSize(new java.awt.Dimension(90, 30));
        plButton.add(btnRefesh);

        lblImg.setBackground(new java.awt.Color(255, 255, 255));
        lblImg.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblImg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pdf.png"))); // NOI18N
        plButton.add(lblImg);

        javax.swing.GroupLayout plHeaderLayout = new javax.swing.GroupLayout(plHeader);
        plHeader.setLayout(plHeaderLayout);
        plHeaderLayout.setHorizontalGroup(
            plHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(plHeaderLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(plSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addComponent(plButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 209, Short.MAX_VALUE))
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        plHeaderLayout.setVerticalGroup(
            plHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(plHeaderLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(plHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(plSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(plButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        add(plHeader, java.awt.BorderLayout.NORTH);

        plCustomerList.setBackground(new java.awt.Color(255, 255, 255));
        plCustomerList.setMaximumSize(new java.awt.Dimension(326589, 326589));
        plCustomerList.setMinimumSize(new java.awt.Dimension(1050, 450));
        plCustomerList.setPreferredSize(new java.awt.Dimension(1200, 450));
        plCustomerList.setLayout(new java.awt.BorderLayout());

        jScrollPane1.setMaximumSize(new java.awt.Dimension(326589, 326589));
        jScrollPane1.setMinimumSize(new java.awt.Dimension(780, 400));
        jScrollPane1.setPreferredSize(new java.awt.Dimension(1180, 400));

        tbCustomerList.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tbCustomerList.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"KH01", "Nguyễn Văn A", "0123456789",  new Float(100.0)},
                {"KH02", "Nguyễn Văn B", "0978465132",  new Float(20.0)},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "MÃ KHÁCH HÀNG", "TÊN KHÁCH HÀNG", "SỐ ĐIỆN THOẠI", "ĐIỂM"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Float.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tbCustomerList.setMaximumSize(new java.awt.Dimension(326589, 326589));
        tbCustomerList.setMinimumSize(new java.awt.Dimension(780, 400));
        tbCustomerList.setPreferredSize(new java.awt.Dimension(1180, 400));
        tbCustomerList.setRowHeight(30);
        tbCustomerList.setShowGrid(true);
        jScrollPane1.setViewportView(tbCustomerList);

        plCustomerList.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        add(plCustomerList, java.awt.BorderLayout.SOUTH);
    }// </editor-fold>//GEN-END:initComponents
private void btnRefeshActionPerformed(java.awt.event.ActionEvent evt) {
    // TODO: xử lý khi nhấn nút Refresh
}

private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {
    // TODO: xử lý khi nhấn nút Thêm
}


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnRefesh;
    private javax.swing.JComboBox<String> cbSort;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblImg;
    private javax.swing.JPanel plButton;
    private javax.swing.JPanel plCustomerList;
    private javax.swing.JPanel plHeader;
    private javax.swing.JPanel plSearch;
    private javax.swing.JTable tbCustomerList;
    private javax.swing.JTextField txtSearch1;
    // End of variables declaration//GEN-END:variables
}
