/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.pharmacy.app.GUI.Employee;

/**
 *
 * @author phong
 */
public class EmployeeManagement extends javax.swing.JPanel {

    /**
     * Creates new form EmployeeManagement
     */
    public EmployeeManagement() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tpEmployeeManagement = new javax.swing.JTabbedPane();
        pnlEmployees = new javax.swing.JPanel();
        pnlEmployee1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        txtSearchEmployee = new javax.swing.JTextField();
        cbEmployee = new javax.swing.JComboBox<>();
        pnlEmployeeButton = new javax.swing.JPanel();
        btnAddEmployee = new javax.swing.JButton();
        btnRefeshEmployee = new javax.swing.JButton();
        btnPdfEmployee = new javax.swing.JButton();
        pnlEmployee2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblEmployees = new javax.swing.JTable();
        pnlContracts = new javax.swing.JPanel();
        pnlContract1 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        txtSearchContract = new javax.swing.JTextField();
        cbContract = new javax.swing.JComboBox<>();
        pnlContractButton = new javax.swing.JPanel();
        btnAddContract = new javax.swing.JButton();
        btnRefeshContract = new javax.swing.JButton();
        btnPdfContract = new javax.swing.JButton();
        pnlContract2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbContracts = new javax.swing.JTable();

        setBackground(new java.awt.Color(255, 255, 255));
        setToolTipText("");
        setPreferredSize(new java.awt.Dimension(1200, 508));
        setLayout(new java.awt.BorderLayout());

        tpEmployeeManagement.setBackground(new java.awt.Color(255, 255, 255));
        tpEmployeeManagement.setPreferredSize(new java.awt.Dimension(1200, 529));

        pnlEmployees.setBackground(new java.awt.Color(255, 255, 255));
        pnlEmployees.setPreferredSize(new java.awt.Dimension(1180, 700));
        pnlEmployees.setLayout(new java.awt.BorderLayout());

        pnlEmployee1.setBackground(new java.awt.Color(255, 255, 255));
        pnlEmployee1.setToolTipText("");
        pnlEmployee1.setPreferredSize(new java.awt.Dimension(1180, 70));
        pnlEmployee1.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 0, 5));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setPreferredSize(new java.awt.Dimension(500, 70));
        jPanel2.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        txtSearchEmployee.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        txtSearchEmployee.setForeground(new java.awt.Color(153, 153, 153));
        txtSearchEmployee.setText("Tìm kiếm");
        txtSearchEmployee.setHighlighter(null);
        txtSearchEmployee.setMinimumSize(new java.awt.Dimension(250, 22));
        txtSearchEmployee.setPreferredSize(new java.awt.Dimension(300, 35));
        txtSearchEmployee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSearchEmployeeActionPerformed(evt);
            }
        });
        jPanel2.add(txtSearchEmployee);

        cbEmployee.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tất cả", "Nam", "Nữ" }));
        cbEmployee.setFocusable(false);
        cbEmployee.setMinimumSize(new java.awt.Dimension(80, 22));
        cbEmployee.setPreferredSize(new java.awt.Dimension(80, 35));
        cbEmployee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbEmployeeActionPerformed(evt);
            }
        });
        jPanel2.add(cbEmployee);

        pnlEmployee1.add(jPanel2);

        pnlEmployeeButton.setBackground(new java.awt.Color(255, 255, 255));
        pnlEmployeeButton.setPreferredSize(new java.awt.Dimension(680, 70));
        pnlEmployeeButton.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT));

        btnAddEmployee.setText("Thêm");
        btnAddEmployee.setFocusable(false);
        btnAddEmployee.setMaximumSize(new java.awt.Dimension(72, 22));
        btnAddEmployee.setMinimumSize(new java.awt.Dimension(72, 22));
        btnAddEmployee.setPreferredSize(new java.awt.Dimension(80, 35));
        btnAddEmployee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddEmployeeActionPerformed(evt);
            }
        });
        pnlEmployeeButton.add(btnAddEmployee);

        btnRefeshEmployee.setText("Tải lại");
        btnRefeshEmployee.setFocusable(false);
        btnRefeshEmployee.setMaximumSize(new java.awt.Dimension(72, 22));
        btnRefeshEmployee.setMinimumSize(new java.awt.Dimension(72, 22));
        btnRefeshEmployee.setPreferredSize(new java.awt.Dimension(80, 35));
        btnRefeshEmployee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefeshEmployeeActionPerformed(evt);
            }
        });
        pnlEmployeeButton.add(btnRefeshEmployee);

        btnPdfEmployee.setText("In PDF");
        btnPdfEmployee.setFocusable(false);
        btnPdfEmployee.setMaximumSize(new java.awt.Dimension(72, 22));
        btnPdfEmployee.setMinimumSize(new java.awt.Dimension(72, 22));
        btnPdfEmployee.setPreferredSize(new java.awt.Dimension(80, 35));
        btnPdfEmployee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPdfEmployeeActionPerformed(evt);
            }
        });
        pnlEmployeeButton.add(btnPdfEmployee);

        pnlEmployee1.add(pnlEmployeeButton);

        pnlEmployees.add(pnlEmployee1, java.awt.BorderLayout.NORTH);

        pnlEmployee2.setBackground(new java.awt.Color(255, 255, 255));
        pnlEmployee2.setPreferredSize(new java.awt.Dimension(600, 439));

        jScrollPane1.setPreferredSize(new java.awt.Dimension(1180, 600));

        tblEmployees.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Mã nhân viên", "Họ tên", "Ngày sinh", "Giới tính", "Email", "SĐT", "Địa chỉ"
            }
        ));
        tblEmployees.setFocusable(false);
        tblEmployees.setMinimumSize(new java.awt.Dimension(500, 80));
        tblEmployees.setPreferredSize(new java.awt.Dimension(1180, 600));
        tblEmployees.setShowGrid(true);
        jScrollPane1.setViewportView(tblEmployees);

        pnlEmployee2.add(jScrollPane1);

        pnlEmployees.add(pnlEmployee2, java.awt.BorderLayout.CENTER);

        tpEmployeeManagement.addTab("Nhân viên", pnlEmployees);

        pnlContracts.setBackground(new java.awt.Color(255, 255, 255));
        pnlContracts.setPreferredSize(new java.awt.Dimension(1200, 800));
        pnlContracts.setLayout(new java.awt.BorderLayout());

        pnlContract1.setBackground(new java.awt.Color(255, 255, 255));
        pnlContract1.setToolTipText("");
        pnlContract1.setPreferredSize(new java.awt.Dimension(1200, 70));
        pnlContract1.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 0, 5));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(600, 70));

        txtSearchContract.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        txtSearchContract.setForeground(new java.awt.Color(153, 153, 153));
        txtSearchContract.setText("Tìm kiếm");
        txtSearchContract.setHighlighter(null);
        txtSearchContract.setMinimumSize(new java.awt.Dimension(250, 22));
        txtSearchContract.setPreferredSize(new java.awt.Dimension(500, 35));
        txtSearchContract.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSearchContractActionPerformed(evt);
            }
        });

        cbContract.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tất cả", "Quản lý", "Nhân viên" }));
        cbContract.setFocusable(false);
        cbContract.setPreferredSize(new java.awt.Dimension(80, 35));
        cbContract.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbContractActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtSearchContract, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbContract, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtSearchContract, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbContract, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(29, Short.MAX_VALUE))
        );

        pnlContract1.add(jPanel1);

        pnlContractButton.setBackground(new java.awt.Color(255, 255, 255));
        pnlContractButton.setPreferredSize(new java.awt.Dimension(600, 70));
        pnlContractButton.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT, 10, 5));

        btnAddContract.setBackground(new java.awt.Color(0, 204, 51));
        btnAddContract.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnAddContract.setForeground(new java.awt.Color(255, 255, 255));
        btnAddContract.setText("Thêm");
        btnAddContract.setFocusable(false);
        btnAddContract.setMaximumSize(new java.awt.Dimension(72, 22));
        btnAddContract.setMinimumSize(new java.awt.Dimension(80, 35));
        btnAddContract.setPreferredSize(new java.awt.Dimension(80, 35));
        btnAddContract.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddContractActionPerformed(evt);
            }
        });
        pnlContractButton.add(btnAddContract);

        btnRefeshContract.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnRefeshContract.setText("Tải lại");
        btnRefeshContract.setFocusable(false);
        btnRefeshContract.setMaximumSize(new java.awt.Dimension(72, 22));
        btnRefeshContract.setMinimumSize(new java.awt.Dimension(80, 35));
        btnRefeshContract.setPreferredSize(new java.awt.Dimension(80, 35));
        btnRefeshContract.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefeshContractActionPerformed(evt);
            }
        });
        pnlContractButton.add(btnRefeshContract);

        btnPdfContract.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnPdfContract.setText("In PDF");
        btnPdfContract.setFocusable(false);
        btnPdfContract.setMaximumSize(new java.awt.Dimension(72, 22));
        btnPdfContract.setMinimumSize(new java.awt.Dimension(80, 35));
        btnPdfContract.setPreferredSize(new java.awt.Dimension(80, 35));
        btnPdfContract.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPdfContractActionPerformed(evt);
            }
        });
        pnlContractButton.add(btnPdfContract);

        pnlContract1.add(pnlContractButton);

        pnlContracts.add(pnlContract1, java.awt.BorderLayout.NORTH);

        pnlContract2.setBackground(new java.awt.Color(255, 255, 255));
        pnlContract2.setPreferredSize(new java.awt.Dimension(1180, 500));

        jScrollPane2.setBackground(new java.awt.Color(255, 255, 255));
        jScrollPane2.setPreferredSize(new java.awt.Dimension(1180, 500));

        tbContracts.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tbContracts.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Mã hợp đồng", "Mã nhân viên", "Ngày ký kết", "Ngày bắt đầu", "Ngày kết thúc", "Chức vụ"
            }
        ));
        tbContracts.setFocusable(false);
        tbContracts.setMinimumSize(new java.awt.Dimension(500, 80));
        tbContracts.setPreferredSize(new java.awt.Dimension(1180, 500));
        tbContracts.setRowHeight(30);
        tbContracts.setShowGrid(true);
        jScrollPane2.setViewportView(tbContracts);

        pnlContract2.add(jScrollPane2);

        pnlContracts.add(pnlContract2, java.awt.BorderLayout.CENTER);

        tpEmployeeManagement.addTab("Hợp đồng", pnlContracts);

        add(tpEmployeeManagement, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void txtSearchEmployeeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSearchEmployeeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSearchEmployeeActionPerformed

    private void cbEmployeeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbEmployeeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbEmployeeActionPerformed

    private void btnAddEmployeeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddEmployeeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAddEmployeeActionPerformed

    private void btnRefeshEmployeeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefeshEmployeeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnRefeshEmployeeActionPerformed

    private void btnPdfEmployeeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPdfEmployeeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnPdfEmployeeActionPerformed

    private void txtSearchContractActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSearchContractActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSearchContractActionPerformed

    private void cbContractActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbContractActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbContractActionPerformed

    private void btnAddContractActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddContractActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAddContractActionPerformed

    private void btnRefeshContractActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefeshContractActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnRefeshContractActionPerformed

    private void btnPdfContractActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPdfContractActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnPdfContractActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddContract;
    private javax.swing.JButton btnAddEmployee;
    private javax.swing.JButton btnPdfContract;
    private javax.swing.JButton btnPdfEmployee;
    private javax.swing.JButton btnRefeshContract;
    private javax.swing.JButton btnRefeshEmployee;
    private javax.swing.JComboBox<String> cbContract;
    private javax.swing.JComboBox<String> cbEmployee;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JPanel pnlContract1;
    private javax.swing.JPanel pnlContract2;
    private javax.swing.JPanel pnlContractButton;
    private javax.swing.JPanel pnlContracts;
    private javax.swing.JPanel pnlEmployee1;
    private javax.swing.JPanel pnlEmployee2;
    private javax.swing.JPanel pnlEmployeeButton;
    private javax.swing.JPanel pnlEmployees;
    private javax.swing.JTable tbContracts;
    private javax.swing.JTable tblEmployees;
    private javax.swing.JTabbedPane tpEmployeeManagement;
    private javax.swing.JTextField txtSearchContract;
    private javax.swing.JTextField txtSearchEmployee;
    // End of variables declaration//GEN-END:variables
}
