/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.pharmacy.app.GUI.Promo;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import javax.swing.table.DefaultTableModel;
import com.pharmacy.app.model.*;

/**
 *
 * @author Giai Cuu Li San
 */
public class HomePromo extends javax.swing.JPanel {
    private ArrayList<Promotion> promoList;
    /**
     * Creates new form HomePromo
     */
    public HomePromo() {
        initComponents();
        promoList = new ArrayList<>();
        loadPromoData();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        cbxAll = new javax.swing.JComboBox<>();
        txtSearch = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        lblPdf = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblPromo = new javax.swing.JTable();

        setBackground(new java.awt.Color(255, 255, 255));
        setMaximumSize(new java.awt.Dimension(700, 600));
        setMinimumSize(new java.awt.Dimension(800, 600));
        setPreferredSize(new java.awt.Dimension(1200, 800));
        setLayout(new java.awt.BorderLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setMaximumSize(new java.awt.Dimension(800, 50));
        jPanel2.setMinimumSize(new java.awt.Dimension(800, 54));
        jPanel2.setPreferredSize(new java.awt.Dimension(100, 100));
        jPanel2.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 0, 20));

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setMinimumSize(new java.awt.Dimension(400, 40));
        jPanel4.setPreferredSize(new java.awt.Dimension(700, 70));
        jPanel4.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 10, 15));

        cbxAll.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cbxAll.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "All", "Active", "IsActive" }));
        cbxAll.setPreferredSize(new java.awt.Dimension(80, 35));
        jPanel4.add(cbxAll);

        txtSearch.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        txtSearch.setText("Search");
        txtSearch.setMinimumSize(new java.awt.Dimension(80, 30));
        txtSearch.setPreferredSize(new java.awt.Dimension(500, 35));
        jPanel4.add(txtSearch);

        jPanel2.add(jPanel4);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setMinimumSize(new java.awt.Dimension(500, 50));
        jPanel3.setPreferredSize(new java.awt.Dimension(500, 70));
        jPanel3.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT, 10, 10));

        jButton2.setBackground(new java.awt.Color(0, 204, 51));
        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Add");
        jButton2.setPreferredSize(new java.awt.Dimension(100, 35));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton2);

        jButton4.setBackground(new java.awt.Color(153, 153, 153));
        jButton4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setText("Refresh");
        jButton4.setPreferredSize(new java.awt.Dimension(100, 35));
        jPanel3.add(jButton4);

        lblPdf.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pdf.png"))); // NOI18N
        lblPdf.setPreferredSize(new java.awt.Dimension(45, 45));
        jPanel3.add(lblPdf);

        jPanel2.add(jPanel3);

        add(jPanel2, java.awt.BorderLayout.PAGE_START);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setMinimumSize(new java.awt.Dimension(800, 550));
        jPanel1.setPreferredSize(new java.awt.Dimension(1200, 650));

        jScrollPane2.setMinimumSize(new java.awt.Dimension(760, 510));
        jScrollPane2.setPreferredSize(new java.awt.Dimension(1180, 620));

        tblPromo.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tblPromo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"KM01", "Sale Ngày Nhà Thuốc VN", null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Mã khuyến mãi", "Tên chương trình", "Loại khuyến mãi", "Ngày bắt đầu", "Ngày kết thúc"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tblPromo.setEnabled(false);
        tblPromo.setMaximumSize(new java.awt.Dimension(700, 600));
        tblPromo.setMinimumSize(new java.awt.Dimension(700, 450));
        tblPromo.setPreferredSize(new java.awt.Dimension(1180, 600));
        tblPromo.setRowHeight(30);
        tblPromo.setShowGrid(true);
        tblPromo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblPromoMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblPromo);

        jPanel1.add(jScrollPane2);

        add(jPanel1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        AddPromo dialog = new AddPromo((JFrame) SwingUtilities.getWindowAncestor(this), true);
        dialog.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void tblPromoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblPromoMouseClicked
        if (evt.getClickCount() == 2){
            int row = tblPromo.rowAtPoint(evt.getPoint());
            showPromoDetails(row);
        }
    }//GEN-LAST:event_tblPromoMouseClicked

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cbxAll;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblPdf;
    private javax.swing.JTable tblPromo;
    private javax.swing.JTextField txtSearch;
    // End of variables declaration//GEN-END:variables

    private void loadPromoData() {
        SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
        
        try {
            // Thêm dữ liệu khuyến mãi vào ArrayList
            promoList.add(new Promotion("KM01", "Sale Ngày Nhà Thuốc VN", "Điểm tích lũy", null, 
                                    null, 1000, 50.0, dateFormat.parse("2025-04-01"), dateFormat.parse("2025-04-10")));
            promoList.add(new Promotion("KM02", "Giảm Giá Ngày Quốc Tế", "Mặt hàng", "Thuốc XYZ", 
                                    15.0, null, null, dateFormat.parse("2025-05-01"), dateFormat.parse("2025-05-05")));
            promoList.add(new Promotion("KM03", "Khuyến Mãi Mùa Hè", "Điểm tích lũy", null, 
                                    null, 500, 25.0, dateFormat.parse("2025-06-01"), dateFormat.parse("2025-06-30")));
        } catch (Exception e) {
            e.printStackTrace();
        }
        
        // Cập nhật bảng với dữ liệu khuyến mãi
        updateTable();
    }

    private void updateTable() {
                DefaultTableModel model = (DefaultTableModel) tblPromo.getModel();

        // Xóa các dòng cũ
        model.setRowCount(0);

        // Duyệt qua danh sách khuyến mãi và thêm dữ liệu vào bảng (chỉ 5 trường cần hiển thị)
        SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
        
        for (Promotion promo : promoList) {
            model.addRow(new Object[]{
                promo.getPromotionId(),  // Mã khuyến mãi
                promo.getProgramName(),   // Tên chương trình khuyến mãi
                promo.getPromotionType(),       // Loại khuyến mãi
                dateFormat.format(promo.getStartDate()), // Ngày bắt đầu
                dateFormat.format(promo.getEndDate())    // Ngày kết thúc
            });
        }
    }

    private void showPromoDetails(int row) {
        Promotion promo = promoList.get(row);
        
        PromoDetail dialog = new PromoDetail((JFrame) SwingUtilities.getWindowAncestor(this), promo);
        dialog.setVisible(true);
        
        // Hiển thị thông tin chi tiết trong một dialog (JOptionPane)
//        String message = "Mã khuyến mãi: " + promo.getPromotionId() + "\n" +
//                         "Tên chương trình: " + promo.getProgramName() + "\n" +
//                         "Loại khuyến mãi: " + promo.getPromotionType() + "\n" +
//                         "Sản phẩm: " + promo.getProduct() + "\n" +
//                         "Phần trăm giảm giá: " + promo.getDiscountPercent() + "%\n" +
//                         "Điểm tích lũy tối thiểu: " + promo.getMinAccumulatedPoints() + "\n" +
//                         "Số tiền giảm: " + promo.getDiscountAmount() + "\n" +
//                         "Ngày bắt đầu: " + new SimpleDateFormat("yyyy-MM-dd").format(promo.getStartDate()) + "\n" +
//                         "Ngày kết thúc: " + new SimpleDateFormat("yyyy-MM-dd").format(promo.getEndDate());
//
//        // Hiển thị thông tin trong một dialog
//        JOptionPane.showMessageDialog(this, message, "Chi tiết khuyến mãi", JOptionPane.INFORMATION_MESSAGE);
    }
    
    
}
